name: Crash
description: The game crashes when triangulator is present
title: "[Crash]: "
labels: ["bug", "crash"]
assignees:
  - falsepattern
body:
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What kind of operating system do you have? (MacOS is unsupported, do not report issues from apple systems)
      options:
        - Windows
        - Linux/BSD
    validations:
      required: true
  - type: dropdown
    id: gpu
    attributes:
      label: GPU
      description: What kind of graphics card do you have? If you have multiple, select the one that minecraft uses, you can usually find it somewhere at the top of the crash report.
      options:
        - AMD
        - NVIDIA
        - Intel
    validations:
      required: true
  - type: input
    id: modpack
    attributes:
      label: Modpack (Optional)
      description: If you used Triangulator in a public modpack, you should include the pack's exact name and version here to make debugging easier.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Game log
      description: Attach the fml-client-latest.log file here.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe how and when you experience this bug.
    validations:
      required: false